# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-SDUM-Renew
version:      0.02
version_from: lib/Acme/SDUM/Renew.pm
installdirs:  site
requires:
    Carp:                          1.04
    Crypt::SSLeay:                 0.53
    File::Temp:                    0.17
    HTML::Form:                    1.054
    HTTP::Cookies:                 1.39
    LWP::UserAgent:                2.033
    Mail::Sender:                  0.8.13
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
